version: "3.8"
services:
  weather:
    build: .
    container_name: weather-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true
